name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: test build
    runs-on:  [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y qt5-default
    - name: configure
      run: |
        pwd
        ls -la .
        mkdir build
        cd build
        cmake .. 
    - name: make
      run: |
        cd build
        make -j$(nproc)
