name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: test build
    runs-on:  [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y libc6 libgcc1 liblastfm5-1 libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5 libqt5widgets5 libstdc++6 moc python3-notify2
    - name: configure
      run: |
        pwd
        ls -la .
        mkdir build
        cd build
        cmake .. 
    - name: make
      run: |
        cd build
        make -j$(nproc)
